<template>
  <Layout>
    <Hero />

    <!-- Start Why Solar -->
    <section class="relative px-4 py-16 sm:px-8 lg:px-16 xl:px-40 2xl:px-64 lg:py-24">
      <div class="flex flex-col lg:flex-row lg:-mx-8">
        <div class="w-full lg:w-1/2 lg:px-8">
          <h2 class="text-3xl leading-tight font-bold mt-4">Solar makes seriously good sense</h2>
          <p
            class="text-lg mt-4 font-semibold"
          >Farming, Business parks, University, Colleges, Schools, Hospitals and more...</p>
          <p
            class="mt-2 leading-relaxed"
          >With a decent roof or plot of land and a long-term intention to stay SOLAR makes good sense. Ideally the you should own the freehold of your premises, or have a long-lease over the property.</p>
          <p
            class="mt-2 leading-relaxed"
          >The lifetime cost per kWh of solar electricity is now 5.5p per kWh... this compares to 10-12p for electricity purchased from the grid.</p>
          <p
            class="mt-2 leading-relaxed"
          >In the right business, the system will more than pay for itself, should be financable if necessary and will significantly improve your company’s impact on the environment.</p>
        </div>

        <div class="w-full lg:w-1/2 lg:px-8 mt-12 lg:mt-8">
          <ul class="text-lg sm:text-xl">
            <li class="checkmark mb-6">
              <div>Lower your energy bills</div>
              <div
                class="text-lg text-gray-600"
              >Save hundreds of pounds each year by powering your home and electric vehicle with cheaper, cleaner and infinite energy generated by the sun, ground or air.</div>
            </li>
            <li class="checkmark mb-6">
              <div>Reduce your carbon footprint and save the planet</div>
              <div
                class="text-lg text-gray-600"
              >Take action and join the fight against our climate crisis by switching away from polluting fossil fuels such as coal, gas and oil.</div>
            </li>
            <li class="checkmark mb-6">
              <div>Gain energy independence</div>
              <div
                class="text-lg text-gray-600"
              >Generate and store your own, clean energy and reduce your reliance on expensive, ‘brown’ energy bought from the National Grid.</div>
            </li>
          </ul>
        </div>
      </div>
    </section>
    <!-- End Why Solar -->

    <!-- Start How it works -->
    <section class="relative bg-gray-100 px-4 sm:px-8 lg:px-16 xl:px-40 2xl:px-64 py-16 lg:py-24">
      <div class="flex flex-col lg:flex-row lg:-mx-8">
        <div class="w-full lg:w-1/2 lg:px-8">
          <h2 class="text-3xl leading-tight font-bold mt-4">How Does Solar Energy Work?</h2>
          <p class="mt-2 leading-relaxed">
            Considered a promising energy source for decades, solar panels can be found on everything from rooftops and roadside signs to stadiums and spacecrafts. Solar energy works by taking energy from the sun and changing it into electricity for homes and businesses.
          </p>
          <p class="mt-2 leading-relaxed">Once solar panels are installed on your roof and begin to create energy, there are a few steps required to turn it into energy your home or business can use. As the sun hits the solar panels, they generate direct current (DC) electricity, where the electrons flow around a circuit in one direction. In order for your home to use this energy, it must be converted from DC electricity to alternating current (AC) electricity, where the electrons are pushed and pulled.</p> 
          <p class="mt-2 leading-relaxed">When you have solar panels installed on your home, you will also have a solar inverter installed. The solar inverter changes the DC output of the solar panels into AC electricity that your home can use.
          </p>
        </div>

        <div class="w-full md:max-w-md md:mx-auto lg:w-1/2 lg:px-8 mt-12 mt:md-0">
        
          <img src="../images/bg-how-it-works.svg" alt="How Solar works">
      </div>
      </div>
    </section>
    <!-- end testimonials -->

    <!-- start blog -->
    <section class="relative bg-white px-4 sm:px-8 lg:px-16 xl:px-40 2xl:px-64 py-24">
      <div class>
        <h2 class="text-3xl leading-tight font-bold">Our Projects</h2>
        <p class="text-gray-600 mt-2 md:max-w-lg">
          Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
          turpis egestas.
        </p>

        <a
          href="#"
          title
          class="inline-block text-teal-500 font-semibold mt-6 mt:md-0"
        >View All Projects</a>
      </div>

      <div class="md:flex mt-12 md:-mx-4">
        <div class="md:px-4 md:w-1/2 xl:w-1/4">
          <div class="bg-white rounded border border-gray-300">
            <div class="w-full h-48 overflow-hidden bg-gray-300">
              <img src="../images/dairy under solar.jpg" alt="">
            </div>
            <div class="p-4">
              <div class="flex items-center text-sm">
                <span class="text-teal-500 font-semibold">Farming</span>
                <span class="ml-4 text-gray-600">29 Nov, 2019</span>
              </div>
              <p class="text-lg font-semibold leading-tight mt-4">Card Title</p>
              <p
                class="text-gray-600 mt-1"
              >This card has supporting text below as a natural lead-in to additional content.</p>
            
            </div>
          </div>
        </div>

        <div class="md:px-4 md:w-1/2 xl:w-1/4 mt-4 md:mt-0">
          <div class="bg-white rounded border border-gray-300">
            <div class="w-full h-48 overflow-hidden bg-gray-300">
              <img src="../images/Sola-Future.jpg" alt="">
            </div>
            <div class="p-4">
              <div class="flex items-center text-sm">
                <span class="text-teal-500 font-semibold">Business</span>
                <span class="ml-4 text-gray-600">29 Nov, 2019</span>
              </div>
              <p class="text-lg font-semibold leading-tight mt-4">Card Title</p>
              <p class="text-gray-600 mt-1">
                This card has supporting text below as a natural lead-in to additional
                content.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- end blog -->

    <!-- Start partners -->
    <section class="relative bg-gray-200 px-4 sm:px-8 lg:px-16 xl:px-40 2xl:px-64 py-24">
      <div class="partners">
        <h2 class="text-3xl leading-tight font-bold">Strategic Partnerships</h2>
        <p class="text-gray-600 mt-2">We have formed strategic partnerships with several local and international suppliers. In doing so we ensure a superior product, unsurpassed service capability, excellent warranties and spare parts availability.</p>
        
        <ul class="flex items-center pt-16">
          <li class="px-4"><img class="w-32" src="../images/SolarEdge_logo.png" alt="Partner company SolarEdge"></li>
          <li class="px-4"><img class="w-40" src="../images/canadianSolar_logo.png" alt="Partner company CanadianSolar "></li>
          <li class="px-4"><img class="w-24" src="../images/SMA_logo.svg" alt="Partner company SMA"></li>
          <li class="px-4"><img class="w-24" src="../images/mecer_logo.png" alt="Partner company Mecer"></li>
        </ul>
      </div>
    </section>

    <!-- start cta -->
    <section
      class="relative bg-blue-teal-gradient px-4 sm:px-8 lg:px-16 xl:px-40 2xl:px-64 py-12 text-center md:text-left">
      <div class="md:flex md:items-center md:justify-center">
        <h2 class="text-xl font-bold text-white">
          Get in touch with us today!
          <br class="block md:hidden" />Call us on: 0825606631

        </h2>
        <a
          href="#"
          class="px-8 py-4 bg-white text-blue-600 rounded inline-block font-semibold md:ml-8 mt-4 md:mt-0"
        >
          Book
          a Solar Consultation
        </a>
      </div>
    </section>
    <!-- end cta -->

  </Layout>
</template>

<script>
import Hero from "../components/Hero";
export default {
  components: {
    Hero
  },
  metaInfo: {
    title: "Hello, world!"
  }
};
</script>

<style>
.home-links a {
  margin-right: 1rem;
}
</style>
