<template>
  <layout>
    <article class="relative bg-gray-100 px-4 sm:px-8 lg:px-16 xl:px-40 2xl:px-64 py-16 lg:py-24">
      <div class="flex flex-col lg:flex-row mt-24">
        <div class="w-full lg:px-8">
          <h1
            class="text-3xl leading-tight font-bold mt-4"
          >Cheaper, greener energy solutions for your home.</h1>
          <div class="text-xl leading-tight capitalize mt-4">BENEFITS OF SWITCHING TO RENEWABLE ENERGY TECHNOLOGIES</div>
          <h2 class="text-l leading-tight font-bold mt-4">Reducing costs and going green</h2>
          <div class="w-full lg:w-1/2 lg:px-8 mt-12 lg:mt-8">
          <ul class="text-lg sm:text-xl">
            <li class="checkmark mb-6">
              <h3 class="bold mt-2">
                Lower your energy bills
              </h3>
              <p class="text-lg text-gray-600">
                Save hundreds of pounds each year by powering your home and electric vehicle with cheaper, cleaner and infinite energy generated by the sun, ground or air.
              </p>
            </li>
            <li class="checkmark mb-6">
              <h3 class="bold mt-2">
                Reduce your carbon footprint and save the planet 
              </h3>
              <p class="text-lg text-gray-600">
                Take action and join the fight against our climate crisis by switching away from polluting fossil fuels such as coal, gas and oil.
              </p>
            </li>
            <li class="checkmark mb-6">
              <h3 class="bold mt-2">
                Gain energy independence
              </h3>
              <p class="text-lg text-gray-600">
                Generate and store your own, clean energy and reduce your reliance on expensive, ‘brown’ energy bought from the National Grid.
              </p>
            </li>
            <li class="checkmark mb-6">
              <h3 class="bold mt-2">
                Secure your energy for the future
              </h3>
              <p class="text-lg text-gray-600">
                Renewable technologies including solar panels allow you to ‘pre-purchase’ your future energy to protect you and your family from future energy price increases.
              </p>
            </li>
            <li class="checkmark mb-6">
              <h3 class="bold mt-2">
                Improve your homes energy rating
              </h3>
              <p class="text-lg text-gray-600">
                Installing solar panels and renewable technologies will increase your homes energy performance and improve your energy performance certificate (EPC)
              </p>
            </li>
          </ul>
          </div>
        
        </div>
      </div>
    </article>
  </layout>
</template>

<script>
export default {};
</script>
